apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-dt
  labels:
    type: local
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/data/prometheus/"