apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  ports:
  - port: 9090
    name: prometheus
  clusterIP: None
  selector:
    app: prometheus
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  serviceName: "prometheus"
  replicas: 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: prometheus
        image: prom/prometheus:v2.19.2
        ports:
        - containerPort: 9090
          name: prometheus
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: data
          mountPath: /prometheus
          readOnly: false
      volumes:
       - name: config-volume
         configMap:
            name: prometheus
            items: 
              - key: prometheus.yml
                path: prometheus.yml
      initContainers:
        - name: "init-prometheus"
          image: prom/prometheus:v2.19.2
          command: ["/bin/chmod","-R","777","/prometheus"]                      
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local"
      resources:
        requests:
          storage: 2Gi
