apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: prometheus-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - image: nginx:1.12
        name: nginx
        ports:
        - containerPort: 9090