kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ps-db3-pvc
  labels:
   app: ps-db3
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi