apiVersion: v1
kind: PersistentVolume
metadata:
  name: ps-db3-pv
  labels:
    type: local
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: "/data/ps-db3"